
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  port: 5432

development:
  <<: *default
  database: categorizer_dev

test:
  <<: *default
  database: categorizer_test

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_URL'] %>